//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "member_notification_message")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub guild_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub join: bool,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub thumbnail_is_file: bool,
    #[sea_orm(column_type = "Text")]
    pub thumbnail_url: String,
    pub image_is_file: bool,
    #[sea_orm(column_type = "Text")]
    pub image_url: String,
    #[sea_orm(column_type = "Text")]
    pub author: String,
    pub author_icon_is_file: bool,
    #[sea_orm(column_type = "Text")]
    pub author_icon_url: String,
    #[sea_orm(column_type = "Text")]
    pub footer: String,
    pub footer_icon_is_file: bool,
    #[sea_orm(column_type = "Text")]
    pub footer_icon_url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
